version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: ciclo-backend
    ports:
      - "8000:8000"
    volumes:
      # Código backend en caliente
      - ./backend/app:/app/app
      - ./backend/requirements.txt:/app/requirements.txt
      
      # Código frontend disponible dentro del contenedor
      - ./frontend:/app/frontend

    environment:
      - ENV=development

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
